### PR TITLE
Add random theme functionality

### PR DESCRIPTION
**Pull request by Kiedtl**
Added a random theme functionality. 

By executing `pshazz use random`, pshazz will use a random theme for each session, or rather each time `pshazz init` is called.

Pshazz will also print which theme was loaded on `pshazz init` if the theme is set to random.

I also fixed the borin theme by adding a space in front of `git_remote_state`.

### CODE REVIEW

**Comment by lukesampson** [comment]
No worries, I've reverted this PR so feel free to submit another one once it's fixed.

**Comment by Kiedtl** [comment]
need a little help here. 
Git keeps adding the 14 themes again, even though no changes have been made:
```
{ pshazz } master * = » git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   themes/borin.json
        modified:   themes/kiedix.json
        modified:   themes/kiedtl.json
        modified:   themes/lambda-simple.json
        modified:   themes/lambda.json
        modified:   themes/linux.json
        modified:   themes/steeef.json
        modified:   themes/unix-lambda.json
        modified:   themes/unix.json
        modified:   themes/ys.json
        modified:   themes/zor.json

no changes added to commit (use "git add" and/or "git commit -a")
{ pshazz } master * = »
```
capture

… and I can't seem to get rid of them...
```
{ pshazz } master * = » git checkout -- themes/borin.json
{ pshazz } master * = » git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   themes/borin.json
        modified:   themes/kiedix.json
        modified:   themes/kiedtl.json
        modified:   themes/lambda-simple.json
        modified:   themes/lambda.json
        modified:   themes/linux.json
        modified:   themes/steeef.json
        modified:   themes/unix-lambda.json
        modified:   themes/unix.json
        modified:   themes/ys.json
        modified:   themes/zor.json

no changes added to commit (use "git add" and/or "git commit -a")
{ pshazz } master * = »
```
This is what the two earlier commits I mentioned were about, and even deleting the old fork and re-forking doesn't seem to fix anything.

Otherwise, the two earlier commits were completely harmless and didn't seem to contain any breaking changes. So I guess if we can't fix this issue we can  perhaps re-merge this one anyway.

**Comment by lukesampson** [comment]
It looks like something to do with CRLF vs LF line breaks. Maybe do a fresh git clone if you just want a clean slate.

**Comment by Kiedtl** [comment]
A fresh git clone did nothing and changed nothing, same store.
maybe its due to this line in the gitattributes file:
```
* text eol=crlf
```
I'm not sure though.

I'm beginning to think that it might be better to just re-merge this PR - the two commits are otherwise completely harmless, and I havn't seen any breaking changes in those commits anyway. The only side-effect of those commits, I think, will be that I will have more additions/deletions to my name than I deserve :grin:

 Can we just re-merge here (or revert the revert)?

**Pull request merged**
