### PR TITLE
Added theme and new line numbers of additions/removals for Git

### PR DESCRIPTION
**Pull request by m0ngr31**
The theme requires a patched version of the Consolas font to work.

2015-09-11 22_52_19-greenshot

### CODE REVIEW

**Comment by ntwb** [comment]
Looks cool, but a question:
> The theme requires a patched version of the Consolas font to work.

Where does one find a patched version of Consolas? Or does the end user patch that themselves?

Maybe adding a comment in the `agnoster.json` file, an example of a theme with a comment is in:
https://github.com/lukesampson/pshazz/blob/master/themes/keepprompt.json

**Comment by m0ngr31** [comment]
I'll make sure and add that. I'm going to update my PR to also move some of the other features into their own plugins so that it's not congesting your code too.

**Comment by Boggin** [comment]
I liked this theme so I used @m0ngr31 code and moved it forward to the latest pshazz. The fork is [here](https://github.com/Boggin/pshazz/commits/master).

**Comment by lukesampson** [comment]
Sorry I've lost track of what's going on here – it looked like there were some more changes coming. This looks good to me though. If you can submit a new PR I'd be happy to merge it. I'll close this one because it's a bit out of date.

**Pull request closed without merging**
