### PR TITLE
Make pshazz Unix-compatible

### PR DESCRIPTION
**Pull request by kiedtl**
Over the past few days, I've been trying to get pshazz running on Linux. One problem I encountered is that pshazz uses the USERPROFILE variable to get the home directory.

The problem with this method is that this environment variable is set on Windows but not on Unix. 
Another problem is that pshazz uses Windows-style paths (`path\to\blah\blah.txt`) instead of Unix-style (`path/to/blah/blah.txt`). Unix cannot tolerate the former but the latter is cross-compatible.

#### Fixes
- [ ] <s>Find out why `pshazz init` doesn't work on Linux and fix it</s> Find out why prompt doesn't work on Linux and fix.
- [x] Change `$env:USERPROFILE` to `${HOME}`
- [x] Change Windows-style paths to Unix-style paths

### CODE REVIEW

**Comment by kiedtl** [comment]
@h404bi We might have to disable plugins (except perhaps git) on Unix systems due to incompatibility with Linux, etc.

What do you think?

**Comment by h404bi** [comment]
Why not make plugins be compatible with Unix.

**Comment by kiedtl** [comment]
> Why not make plugins be compatible with Unix.

Correct - would be the proper solution. I mean for now - in another pull request plugins can be made Unix-compatible. 

BTW SSH plugin will have to be disabled on Unix indefinitely, as it relies on Windows binaries (`askpass.exe`).

**Comment by kiedtl** [comment]
OK - I hate to say this, but pshazz is **not**, flat out **NOT** compatible with anything other than Windows. I guess I'm giving up - pshazz doesn't need a PR, it needs an entire rewrite before it will be truly cross-platform. And the many quirks and differences between Windows and Linux further complicate matters.

**Pull request closed without merging**
